[versions]
kotlin = "2.4.10"
kotlinx-coroutines = "1.11.0"

shadow = "9.5.1"
minotaur = "2.9.0"
blossom = "2.2.0"

simplecloud-api = "0.1.0-platform.40"
simplecloud-plugin = "0.0.1-platform.1778966459069-b1e45e2"

velocity = "4.1.0-SNAPSHOT"
bungeecord-api = "1.21-R0.4"

adventure-api = "5.2.0"
adventure-platform-bungeecord = "4.4.1"

configurate = "4.2.0"

cloud-core = "2.0.0"
cloud-velocity = "2.0.0-beta.10"
cloud-bungeecord = "2.0.0-beta.10"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

simplecloud-api = { module = "app.simplecloud.api:api", version.ref = "simplecloud-api" }
simplecloud-plugin = { module = "app.simplecloud.plugin:plugin-shared", version.ref = "simplecloud-plugin" }

velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord-api" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-platform-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-platform-bungeecord" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure-api" }

configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }

cloud-command-core = { module = "org.incendo:cloud-core", version.ref = "cloud-core" }
cloud-command-velocity = { module = "org.incendo:cloud-velocity", version.ref = "cloud-velocity" }
cloud-command-bungeecord = { module = "org.incendo:cloud-bungee", version.ref = "cloud-bungeecord" }

[bundles]
adventure = ["adventure-api", "adventure-text-minimessage", "adventure-text-serializer-legacy"]
configurate = ["configurate-yaml", "configurate-kotlin"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }