[versions]
kotlin = "1.8.0"
shadow = "8.1.1"
velocity = "3.1.1"
bungeecord = "1.19-R0.1-SNAPSHOT"
adventure = "4.16.0"
adventurelatform = "4.3.2"
gson = "2.10.1"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
velocityApi = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungeecordApi = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }
adventureLegacySerializer = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventureApi = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventureBungeecordPlatform = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventurelatform" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }