name: proxy-essentials-bungeecord
main: app.simplecloud.plugin.proxy.bungeecord.ProxyBungeeCordPlugin
version: ${version}
author: D151l
description: Configure SimpleCloud MOTDs, tablists, join states, player counts, and proxy layouts
depends: [simplecloud-api]