current-date-format: "dd.MM.yyyy"
current-time-format: "HH:mm:ss"
ping-colors:
  - ping: 0
    color: "<green>"
  - ping: 50
    color: "<yellow>"
  - ping: 100
    color: "<gold>"
  - ping: 150
    color: "<red>"
  - ping: 200
    color: "<dark_red>"
